In [1]:
import numpy as np

In [2]:
X = np.array([[0, 0], [1, 0], [0, 1], [1, 1]])

In [3]:
z_reg = np.array([-0.2, -0.05, -0.05, 0.1])

In [4]:
X.shape

(4, 2)

In [5]:
z_reg

array([-0.2 , -0.05, -0.05,  0.1 ])

In [6]:
# 单层回归网络

def linearR(x1, x2):
    """
    x1, x2 为两个特征矩阵
    """
    w1, w2, b = 0.15, 0.15, -0.2
    z = x1 * w1 + x2 * w2 + b
    return z

In [7]:
linearR(X[:, 0], X[:, 1])

array([-0.2 , -0.05, -0.05,  0.1 ])

In [9]:
# 单层分类网络

# 预测与门
y_and = [0, 0, 0, 1]

In [15]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [16]:
def AND_sigmoid(x1, x2):
    w1, w2, b = 0.15, 0.15, -0.2
    z = x1 * w1 + x2 * w2 + b
    o = sigmoid(z)
    y = [int(x) for x in o >= 0.5]
    return o, y

In [17]:
o, y_sigm = AND_sigmoid(X[:, 0], X[:, 1])

In [19]:
o

array([0.450166  , 0.4875026 , 0.4875026 , 0.52497919])

In [20]:
y_sigm

[0, 0, 0, 1]

In [21]:
def AND(x1, x2):
    w1, w2, b = 0.15, 0.15, -0.23
    z = x1 * w1 + x2 * w2 + b
    y = [int(x) for x in z >= 0]
    return y

In [22]:
X

array([[0, 0],
       [1, 0],
       [0, 1],
       [1, 1]])

In [23]:
AND(X[:, 0], X[:, 1])

[0, 0, 0, 1]

In [24]:
z = np.array([1010, 1000, 990])
np.exp(z) / np.sum(np.exp(z))

/home/ppp/anaconda3/envs/python-3.6/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  
/home/ppp/anaconda3/envs/python-3.6/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan, nan, nan])

In [26]:
c = np.max(z)
print(c)

1010


In [27]:
def softmax(z):
    c = np.max(z)
    exp_z = np.exp(z - c)
    sum_exp_z = np.sum(exp_z)
    o = exp_z / sum_exp_z
    return o

In [28]:
softmax(z)

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])