In [1]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [2]:
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]

In [3]:
data

[[-1, 2], [-0.5, 6], [0, 10], [1, 18]]

In [5]:
import pandas as pd

In [6]:
pd.DataFrame(data)

0   1
0 -1.0   2
1 -0.5   6
2  0.0  10
3  1.0  18

In [7]:
# 归一化

scaler = MinMaxScaler() # 实例化
scaler = scaler.fit(data) # fit，计算 min(x) 和 max(x)
result = scaler.transform(data) # 导出结果
result

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [8]:
result_ = scaler.fit_transform(data) # 训练和导出结果一步完成
result_

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [9]:
scaler.inverse_transform(result)

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [10]:
# feature_range 参数
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
scaler = MinMaxScaler(feature_range=[5, 10])

In [11]:
result = scaler.fit_transform(data)
result

array([[ 5.  ,  5.  ],
       [ 6.25,  6.25],
       [ 7.5 ,  7.5 ],
       [10.  , 10.  ]])

In [12]:
# numpy 实现归一化
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
X = np.array(data)

# 归一化
X_nor = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
X_nor

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [13]:
# 逆归一化
X_returned = X_nor * (X.max(axis=0) - X.min(axis=0)) + X.min(axis=0)
X_returned

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [14]:
# 标准化

from sklearn.preprocessing import StandardScaler

In [15]:
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]

scaler = StandardScaler()
scaler.fit(data) # 求均值和方差

StandardScaler()

In [16]:
scaler.mean_

array([-0.125,  9.   ])

In [17]:
scaler.var_

array([ 0.546875, 35.      ])

In [19]:
x_std = scaler.transform(data) # 导出结果
x_std

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

In [20]:
x_std.mean()

0.0

In [21]:
x_std.std()

1.0

In [22]:
scaler.fit_transform(data)

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

In [23]:
scaler.inverse_transform(x_std)

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [45]:
# 缺失值
from sklearn.impute import SimpleImputer

import pandas as pd
data = pd.read_csv("data/Narrativedata.csv", index_col=0)
data.head()

Age     Sex Embarked Survived
0  22.0    male        S       No
1  38.0  female        C      Yes
2  26.0  female        S      Yes
3  35.0  female        S      Yes
4  35.0    male        S       No

In [68]:
data.info()

#填补年龄
Age = data.loc[:,"Age"].values.reshape(-1,1)

#sklearn当中特征矩阵必须是二维
Age[:20]
from sklearn.impute import SimpleImputer
imp_mean = SimpleImputer() #实例化,默认均值填补
imp_median = SimpleImputer(strategy="median") #用中位数填补
imp_0 = SimpleImputer(strategy="constant",fill_value=0) #用0填补
imp_mean = imp_mean.fit_transform(Age)

#fit_transform一步完成调取结果
imp_median = imp_median.fit_transform(Age)
imp_0 = imp_0.fit_transform(Age)

imp_mean[:20]
imp_median[:20]
imp_0[:20]

#在这里我们使用中位数填补Age
data.loc[:,"Age"] = imp_median

data.info()

#使用众数填补Embarked
Embarked = data.loc[:,"Embarked"].values.reshape(-1,1)

imp_mode = SimpleImputer(strategy = "most_frequent")
data.loc[:,"Embarked"] = imp_mode.fit_transform(Embarked)
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       891 non-null    float64
 1   Sex       891 non-null    object 
 2   Embarked  891 non-null    object 
 3   Survived  891 non-null    int64  
dtypes: float64(1), int64(1), object(2)
memory usage: 34.8+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       891 non-null    float64
 1   Sex       891 non-null    object 
 2   Embarked  891 non-null    object 
 3   Survived  891 non-null    int64  
dtypes: float64(1), int64(1), object(2)
memory usage: 34.8+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       8

In [69]:
# 处理分类型特征

# 1. 标签：文字型转数值型
from sklearn.preprocessing import LabelEncoder

In [70]:
data

Age     Sex Embarked  Survived
0    22.0    male        S         0
1    38.0  female        C         2
2    26.0  female        S         2
3    35.0  female        S         2
4    35.0    male        S         0
..    ...     ...      ...       ...
886  27.0    male        S         0
887  19.0  female        S         2
888  28.0  female        S         0
889  26.0    male        C         1
890  32.0    male        Q         0

[891 rows x 4 columns]

In [71]:
# 选取最后一列
y = data.iloc[:, -1]
y

0      0
1      2
2      2
3      2
4      0
      ..
886    0
887    2
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [72]:
le = LabelEncoder()
le.fit(y)
label = le.transform(y)

In [73]:
le.classes_

array([0, 1, 2])

In [74]:
# 获取的结果 label
label

array([0, 2, 2, 2, 0, 0, 0, 0, 2, 2, 1, 2, 0, 0, 0, 1, 0, 2, 0, 2, 1, 2,
       2, 2, 0, 1, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 1,
       2, 0, 0, 2, 0, 0, 0, 0, 2, 2, 0, 2, 2, 0, 2, 0, 0, 2, 0, 0, 0, 2,
       2, 0, 2, 0, 0, 0, 0, 0, 2, 1, 0, 1, 2, 2, 0, 2, 2, 0, 2, 2, 0, 0,
       2, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 2,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 2, 2, 0, 1, 0,
       0, 2, 0, 0, 2, 0, 0, 0, 1, 1, 2, 0, 0, 0, 2, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 1, 0, 2, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 2, 0, 2, 2, 0, 0, 2, 0, 2, 1, 2, 2, 0, 0,
       1, 0, 0, 0, 0, 0, 2, 0, 0, 2, 2, 2, 1, 2, 1, 0, 0, 2, 2, 0, 2, 0,
       2, 0, 0, 0, 2, 0, 2, 0, 0, 0, 2, 1, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2,
       0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 1, 0, 2, 2, 2, 2, 2, 0, 2, 0, 1,
       0, 0, 1, 2, 2, 1, 0, 2, 2, 0, 2, 2, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0,
       2, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2, 2, 2,

In [75]:
# 简洁写法
data.iloc[:, -1] = LabelEncoder().fit_transform(data.iloc[:, -1])

In [76]:
data

Age     Sex Embarked  Survived
0    22.0    male        S         0
1    38.0  female        C         2
2    26.0  female        S         2
3    35.0  female        S         2
4    35.0    male        S         0
..    ...     ...      ...       ...
886  27.0    male        S         0
887  19.0  female        S         2
888  28.0  female        S         0
889  26.0    male        C         1
890  32.0    male        Q         0

[891 rows x 4 columns]

In [77]:
# 特征，分类特征转分类数值

from sklearn.preprocessing import OrdinalEncoder

In [78]:
data_ = data.copy()
data_

Age     Sex Embarked  Survived
0    22.0    male        S         0
1    38.0  female        C         2
2    26.0  female        S         2
3    35.0  female        S         2
4    35.0    male        S         0
..    ...     ...      ...       ...
886  27.0    male        S         0
887  19.0  female        S         2
888  28.0  female        S         0
889  26.0    male        C         1
890  32.0    male        Q         0

[891 rows x 4 columns]

In [79]:
OrdinalEncoder().fit(data_.iloc[:, 0:-1]).categories_

[array([ 0.42,  0.67,  0.75,  0.83,  0.92,  1.  ,  2.  ,  3.  ,  4.  ,
         5.  ,  6.  ,  7.  ,  8.  ,  9.  , 10.  , 11.  , 12.  , 13.  ,
        14.  , 14.5 , 15.  , 16.  , 17.  , 18.  , 19.  , 20.  , 20.5 ,
        21.  , 22.  , 23.  , 23.5 , 24.  , 24.5 , 25.  , 26.  , 27.  ,
        28.  , 28.5 , 29.  , 30.  , 30.5 , 31.  , 32.  , 32.5 , 33.  ,
        34.  , 34.5 , 35.  , 36.  , 36.5 , 37.  , 38.  , 39.  , 40.  ,
        40.5 , 41.  , 42.  , 43.  , 44.  , 45.  , 45.5 , 46.  , 47.  ,
        48.  , 49.  , 50.  , 51.  , 52.  , 53.  , 54.  , 55.  , 55.5 ,
        56.  , 57.  , 58.  , 59.  , 60.  , 61.  , 62.  , 63.  , 64.  ,
        65.  , 66.  , 70.  , 70.5 , 71.  , 74.  , 80.  ]),
 array(['female', 'male'], dtype=object),
 array(['C', 'Q', 'S'], dtype=object)]

In [91]:
# 独热编码

from sklearn.preprocessing import OneHotEncoder

X = data.iloc[:, 1:-1]

In [92]:
X

Sex Embarked
0      male        S
1    female        C
2    female        S
3    female        S
4      male        S
..      ...      ...
886    male        S
887  female        S
888  female        S
889    male        C
890    male        Q

[891 rows x 2 columns]

In [93]:
enc = OneHotEncoder(categories="auto").fit(X)
result = enc.transform(X)

In [94]:
# 可以还原
pd.DataFrame(enc.inverse_transform(result))

0  1
0      male  S
1    female  C
2    female  S
3    female  S
4      male  S
..      ... ..
886    male  S
887  female  S
888  female  S
889    male  C
890    male  Q

[891 rows x 2 columns]

In [95]:
type(result)

scipy.sparse.csr.csr_matrix

In [96]:
# 返回每一个稀疏矩阵中的列的名字
enc.get_feature_names()

array(['x0_female', 'x0_male', 'x1_C', 'x1_Q', 'x1_S'], dtype=object)

In [97]:
result.shape

(891, 5)

In [98]:
new_data = pd.concat([data, pd.DataFrame(result)], axis=1)
new_data

Age     Sex Embarked  Survived                             0
0    22.0    male        S         0    (0, 1)\t1.0\n  (0, 4)\t1.0
1    38.0  female        C         2    (0, 0)\t1.0\n  (0, 2)\t1.0
2    26.0  female        S         2    (0, 0)\t1.0\n  (0, 4)\t1.0
3    35.0  female        S         2    (0, 0)\t1.0\n  (0, 4)\t1.0
4    35.0    male        S         0    (0, 1)\t1.0\n  (0, 4)\t1.0
..    ...     ...      ...       ...                           ...
886  27.0    male        S         0    (0, 1)\t1.0\n  (0, 4)\t1.0
887  19.0  female        S         2    (0, 0)\t1.0\n  (0, 4)\t1.0
888  28.0  female        S         0    (0, 0)\t1.0\n  (0, 4)\t1.0
889  26.0    male        C         1    (0, 1)\t1.0\n  (0, 2)\t1.0
890  32.0    male        Q         0    (0, 1)\t1.0\n  (0, 3)\t1.0

[891 rows x 5 columns]

In [100]:
# 处理连续性特征

# 二值化
data_2 = data.copy()
data_2

Age     Sex Embarked  Survived
0    22.0    male        S         0
1    38.0  female        C         2
2    26.0  female        S         2
3    35.0  female        S         2
4    35.0    male        S         0
..    ...     ...      ...       ...
886  27.0    male        S         0
887  19.0  female        S         2
888  28.0  female        S         0
889  26.0    male        C         1
890  32.0    male        Q         0

[891 rows x 4 columns]

In [101]:
from sklearn.preprocessing import Binarizer

In [103]:
X = data_2.iloc[:, 0].values.reshape(-1, 1)

In [104]:
X

array([[22.  ],
       [38.  ],
       [26.  ],
       [35.  ],
       [35.  ],
       [28.  ],
       [54.  ],
       [ 2.  ],
       [27.  ],
       [14.  ],
       [ 4.  ],
       [58.  ],
       [20.  ],
       [39.  ],
       [14.  ],
       [55.  ],
       [ 2.  ],
       [28.  ],
       [31.  ],
       [28.  ],
       [35.  ],
       [34.  ],
       [15.  ],
       [28.  ],
       [ 8.  ],
       [38.  ],
       [28.  ],
       [19.  ],
       [28.  ],
       [28.  ],
       [40.  ],
       [28.  ],
       [28.  ],
       [66.  ],
       [28.  ],
       [42.  ],
       [28.  ],
       [21.  ],
       [18.  ],
       [14.  ],
       [40.  ],
       [27.  ],
       [28.  ],
       [ 3.  ],
       [19.  ],
       [28.  ],
       [28.  ],
       [28.  ],
       [28.  ],
       [18.  ],
       [ 7.  ],
       [21.  ],
       [49.  ],
       [29.  ],
       [65.  ],
       [28.  ],
       [21.  ],
       [28.5 ],
       [ 5.  ],
       [11.  ],
       [22.  ],
       [38.  ],
       [

In [121]:
transformer = Binarizer(threshold=30).fit_transform(X)

In [106]:
transformer

array([[0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],

In [107]:
# 分箱

from sklearn.preprocessing import KBinsDiscretizer

In [111]:
X = data.iloc[:, 0].values.reshape(-1, 1)

In [122]:
est = KBinsDiscretizer(n_bins=3, encode="ordinal", strategy="uniform")

In [123]:
est.fit_transform(X)

array([[0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [2.],
       [0.],
       [1.],
       [0.],
       [0.],
       [2.],
       [0.],
       [1.],
       [0.],
       [2.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [2.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [2.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],

In [133]:
set(est.fit_transform(X).ravel())

{0.0, 1.0}

In [134]:
est.fit_transform(X)

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       ...,
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [135]:
est = KBinsDiscretizer(n_bins=3, encode="onehot", strategy="uniform")

In [136]:
est.fit_transform(X)

<891x3 sparse matrix of type '<class 'numpy.float64'>'
	with 891 stored elements in Compressed Sparse Row format>

In [137]:
est = KBinsDiscretizer(n_bins=3, encode="onehot-dense", strategy="uniform")

In [138]:
est.fit_transform(X)

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       ...,
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])